# d2 --theme 1 --sketch <file>

direction: right

GNU Aspell -> Enchant
HunSpell -> Enchant
AppleSpell -> Enchant

"..." -> Enchant

Enchant.shape: circle

Enchant -> "jinx.el"

"jinx.el": {
  style.border-radius: 8
}
